[package]
name = "mm2_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
# decrypt prefab csv files
bytemuck = "1.16.1"
clap = { version = "4.5.7", features = ["derive"] }

# parse serialized haxe files
base64 = "0.22.1"
percent-encoding = "2.3.1"
winnow = "0.6.13"
